### ISSUE TITLE
Rails Static Request

### ISSUE THREAD

**Issue by boom100100** [learn-co-curriculum/rails-hello-world-lab#22] opened 2019-11-12 21:15 UTC
The lab before rails hello world, rails static request, throws a 500 error. Reloading, closing and reopening the browser, and deleting cache didn't fix the issue.

<img width="347" alt="Screen Shot 2019-11-12 at 4 11 11 PM" src="https://user-images.githubusercontent.com/18746369/68711252-47a53080-0567-11ea-9872-cbe4be5e84ad.png">
<img width="791" alt="Screen Shot 2019-11-12 at 4 14 25 PM" src="https://user-images.githubusercontent.com/18746369/68711401-8c30cc00-0567-11ea-94f8-1393ed02bc03.png">

**Comment by boom100100** [comment] 2019-11-12 21:16
I didn't know how to find the github repository for that lab, so I posted it here. I'll repost in the appropriate spot if you send me a link.

**Comment by lizbur10** [comment] 2020-04-01 18:46
Hi there,

I'm unable to reproduce the issue, so I'm going to close it for now.

If you do not believe that the issue has been resolved, please re-open this issue. 💙

As always, thanks for contributing! 💙

**Closed by lizbur10** 2020-04-01 18:46 UTC
